name: AntiAC
version: ${revision}
main: de.bsommerfeld.antiac.AntiAC
api-version: '1.13' # support as many versions as possible
libraries:
  # Hibernate Dependencies
  - "org.hibernate.orm:hibernate-core:6.6.1.Final"
  - "mysql:mysql-connector-java:8.0.32"
  - "jakarta.persistence:jakarta.persistence-api:3.1.0"

commands:
  antiac:
    description: Main command for AntiAC
    usage: /antiac <subcommand>
